export const GET_RATE = 'GET_RATE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const SET_SENDING_AMOUNT = 'SET_SENDING_AMOUNT';
export const SET_RECEIVING_AMOUNT = 'SET_RECEIVING_AMOUNT';
export const SET_SENDING_INPUT = 'SET_SENDING_INPUT';
export const SET_RECEIVING_INPUT = 'SET_RECEIVING_INPUT';
export const CALCULATE_SENDING_AMOUNT = 'CALCULATE_SENDING_AMOUNT';
export const CALCULATE_RECEIVING_AMOUNT = 'CALCULATE_RECEIVING_AMOUNT';
